# Generated by Django 5.0.4 on 2024-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
