# Generated by Django 5.0.4 on 2024-04-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_users_username'),
    ]

    operations = [
    ]
