# Generated by Django 5.0.4 on 2024-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20240419_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
