# Generated by Django 5.0.4 on 2024-04-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('user_management', '0006_rename_users_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Users',
        ),
    ]
