# Generated by Django 5.0.4 on 2024-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_users_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
